/*
MAGNITUDE ANALYSIS:
Purpose:
- The purpose of this script is to quantify the data and group results by specific dimensions.
- This helps in understanding the distribution of data across various categories
SQL Functions Used:
- SUM(), COUNT(), AVG()
- GROUP BY, ORDER BY
 */
-- Retrieve the total number of customers by country
-- Insights:
-- This query shows that most customers are from the USA, followed by Canada and the UK.
-- This information can help in targeting marketing efforts and understanding market demographics.
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM
    gold.dim_customers
GROUP BY
    country
ORDER BY
    total_customers DESC
;


-- Retrieve the total number of customers by gender
-- Insights:
-- This query shows that slightly more customers are men, though the difference is not large.
-- This information can help in tailoring marketing strategies and product offerings.
SELECT
    gender,
    COUNT(gender) AS total_gender
FROM
    gold.dim_customers
GROUP BY
    gender
ORDER BY
    total_gender DESC
;


-- Retrieve the total number of products by category
-- Insights:
-- This query shows that the Components category has the highest number of products, followed by Bikes, then Clothing
-- This information can help in inventory management and product development strategies.
SELECT
    category,
    COUNT(product_key) AS total_products
FROM
    gold.dim_products
GROUP BY
    category
ORDER BY
    total_products DESC
;


-- Retrieve the average cost of products in each category
-- Insights:
-- This query shows that Bikes have the highest average cost, followed by Components, then Clothing.
-- This information can help in pricing strategies and understanding market positioning.
SELECT
    category,
    ROUND(AVG(COST), 2) AS average_cost
FROM
    gold.dim_products
GROUP BY
    category
ORDER BY
    average_cost DESC
;


-- Retrieve the total revenue generated for each product category
-- Insights:
-- This query shows that Bikes generate the highest total revenue, followed by Components, then Clothing.
SELECT
    p.category,
    SUM(s.sales_amount) AS total_revenue
FROM
    gold.fact_sales AS s
    LEFT JOIN gold.dim_products AS p ON p.product_key = s.product_key
GROUP BY
    p.category
ORDER BY
    total_revenue DESC
;


-- Retrieve the total revenue generated by each customer
-- Insights:
-- This query shows the total revenue generated by each customer, with the highest revenue at the top
-- This information can help in identifying high-value customers and tailoring marketing efforts accordingly.
SELECT DISTINCT
    s.customer_key,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(s.sales_amount) AS total_revenue
FROM
    gold.fact_sales AS s
    LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
GROUP BY
    s.customer_key,
    customer_name
ORDER BY
    total_revenue DESC
;


-- Retrieve the total revenue generated by each country
-- Insights:
-- This query shows that the USA generates the highest total revenue, followed by Australia, then the United Kingdom.
-- This information can help in understanding market performance and targeting efforts in high-revenue regions.
SELECT
    c.country,
    SUM(s.sales_amount) AS total_revenue
FROM
    gold.fact_sales AS s
    LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
GROUP BY
    c.country
ORDER BY
    total_revenue DESC
;


-- Retrieve the distribution of sold items across each country
-- Insights:
-- This query shows that the USA has the highest number of items sold, followed by Australia, then Canada
-- This information can help in understanding market demand and tailoring inventory and marketing strategies accordingly. 
SELECT
    c.country,
    SUM(s.quantity) AS total_items_sold
FROM
    gold.fact_sales AS s
    LEFT JOIN gold.dim_customers AS c ON c.customer_key = s.customer_key
GROUP BY
    c.country
ORDER BY
    total_items_sold DESC
;